format_version: 4
common:
  deploy_job: &deploy_job
    resources:
      - docker
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan_certs create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks wait_ecs
  common_stages: &common_stages
    - promote_docker_image:
        resources:
          - docker
        clean_workspace: true
        tasks:
          - exec:
              command: /bin/bash
              arguments:
                - -c
                - ./tasks promote_docker_image
    - deploy:
        clean_workspace: true
        jobs:
          deploy: *deploy_job
    - test:
        clean_workspace: true
        jobs:
          functional:
            resources:
              - docker
            tasks:
              - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks test_functional
          e2e:
            resources:
              - docker
            tasks:
              - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks test_e2e
pipelines:
  'prm-deductions-gp2gp-adaptor.dev':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      app:
        pipeline: prm-deductions-gp2gp-adaptor
        stage: test_docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_dev
      mhs:
        pipeline: prm-mhs-infra.dev
        stage: deploy
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages: *common_stages

  'prm-deductions-gp2gp-adaptor.test':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      dev_env:
        # This dependency ensures gp2gp-adaptor is not deployed to test env if
        # the E2E tests did not pass in the dev environment
        pipeline: prm-deductions-gp2gp-adaptor.dev
        stage: test
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_test
      mhs:
        pipeline: prm-mhs-infra.test
        stage: deploy
    environment_variables:
      NHS_ENVIRONMENT: test
    stages: *common_stages

  'prm-deductions-gp2gp-adaptor.pre-prod':
    group: deductions
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      test_env:
        # This dependency ensures gp2gp-adaptor is not deployed to pre-prod env if
        # the E2E tests did not pass in the test environment
        pipeline: prm-deductions-gp2gp-adaptor.test
        stage: test
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_pre_prod
      mhs:
        pipeline: prm-mhs-infra.pre-prod
        stage: deploy
    environment_variables:
      NHS_ENVIRONMENT: pre-prod
    stages: *common_stages

